#!/usr/bin/env bash
set -euo pipefail

APP_DIR="${AI_COUNCIL_APP_DIR:-/opt/ai-council}"
REPOSITORY="${AI_COUNCIL_GITHUB_REPO:-crazyathlete220-stack/ai-council}"
LABEL="${AI_COUNCIL_GITHUB_JOB_LABEL:-vps-job}"
STATE_ROOT="${AI_COUNCIL_GITHUB_BRIDGE_STATE_ROOT:-/var/lib/ai-council/github-bridge}"
LOG_DIR="${AI_COUNCIL_GITHUB_BRIDGE_LOG_DIR:-/var/log/ai-council/github-bridge}"
REGISTRY_DIR="${AI_COUNCIL_WORKSPACE_REGISTRY_DIR:-/etc/ai-council/workspaces.d}"
IMPORT_DIR="${STATE_ROOT}/imported"
REJECT_DIR="${STATE_ROOT}/rejected"
BLOCKED_DIR="${STATE_ROOT}/blocked"
REJECT_LOG="${LOG_DIR}/rejected-issues.log"
ALLOWLIST_FILE="${AI_COUNCIL_GITHUB_ALLOWED_USERS_FILE:-/etc/ai-council/github-bridge-allowlist}"
MAX_ISSUES="${AI_COUNCIL_GITHUB_IMPORT_LIMIT:-100}"

mkdir -p "${IMPORT_DIR}" "${REJECT_DIR}" "${BLOCKED_DIR}" "${LOG_DIR}"

derive_casual_job() {
  local request_text="$1"
  local request_text_lc=""

  request_text_lc="$(printf "%s" "${request_text}" | tr "[:upper:]" "[:lower:]")"

  if printf "%s" "${request_text_lc}" | grep -Eq "ai_plan|計画|作戦|方針|plan|プラン"; then
    job_type="ai_plan"
    repo_name="ai-council"
    return 0
  fi
  if printf "%s" "${request_text_lc}" | grep -Eq "ai_check|検証|安全確認して|安全確認を|安全に確認|チェックだけ|確認だけ|check only"; then
    job_type="ai_check"
    repo_name="ai-council"
    return 0
  fi
  if printf "%s" "${request_text_lc}" | grep -Eq "workspace_summary|作業場|ワークスペース|workspace|一覧|まとめ|サマリー"; then
    job_type="workspace_summary"
    repo_name="all"
    return 0
  fi
  if printf "%s" "${request_text_lc}" | grep -Eq "repo_check|ai-council.*(状態|確認|チェック)|ヘルス|health|repo|リポジトリ"; then
    job_type="repo_check"
    repo_name="ai-council"
    return 0
  fi
  return 1
}

author_allowed() {
  local author="$1"
  local author_lc=""
  local allowed_seen=0
  local line=""
  local line_lc=""

  [[ -r "${ALLOWLIST_FILE}" ]] || return 2
  author_lc="$(printf "%s" "${author}" | tr "[:upper:]" "[:lower:]")"

  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line%%#*}"
    line="$(printf "%s" "${line}" | tr -d "[:space:]")"
    [[ -n "${line}" ]] || continue
    allowed_seen=1
    [[ "${line}" =~ ^[A-Za-z0-9-]+$ ]] || continue
    line_lc="$(printf "%s" "${line}" | tr "[:upper:]" "[:lower:]")"
    [[ "${line_lc}" == "${author_lc}" ]] && return 0
  done < "${ALLOWLIST_FILE}"

  [[ "${allowed_seen}" -ne 0 ]] || return 3
  return 1
}

post_issue_state() {
  local issue_number="$1"
  local state="$2"
  local detail="$3"
  local body=""

  # detail is generated by this script; %b turns controlled \n separators into
  # real Markdown line breaks without evaluating shell code.
  body="$(printf '## VPS job state\n\nSTATE: %s\n%b\n' "${state}" "${detail}")"
  if ! gh issue comment "${issue_number}" --repo "${REPOSITORY}" --body "${body}" >/dev/null 2>&1; then
    printf "%s issue=%s state=%s reason=github_comment_failed\n" \
      "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" "${issue_number}" "${state}" >> "${LOG_DIR}/state-comment-errors.log"
    return 1
  fi
}

reject_issue() {
  local issue_number="$1"
  local issue_author="$2"
  local reason="$3"
  local rejected_marker="${REJECT_DIR}/issue-${issue_number}.rejected"

  if [[ ! -f "${rejected_marker}" ]]; then
    {
      printf "REJECTED_AT=%s\n" "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
      printf "ISSUE_NUMBER=%s\n" "${issue_number}"
      printf "ISSUE_AUTHOR=%s\n" "${issue_author}"
      printf "REASON=%s\n" "${reason}"
    } > "${rejected_marker}"
    printf "%s issue=%s author=%s reason=%s\n" \
      "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" "${issue_number}" "${issue_author}" "${reason}" >> "${REJECT_LOG}"
    post_issue_state "${issue_number}" "REJECTED" "Reason: ${reason}" || true
  fi
}

block_issue() {
  local issue_number="$1"
  local issue_author="$2"
  local reason="$3"
  local repo_name="$4"
  local blocked_marker="${BLOCKED_DIR}/issue-${issue_number}.blocked"

  if [[ ! -f "${blocked_marker}" ]]; then
    {
      printf "BLOCKED_AT=%s\n" "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
      printf "ISSUE_NUMBER=%s\n" "${issue_number}"
      printf "ISSUE_AUTHOR=%s\n" "${issue_author}"
      printf "REASON=%s\n" "${reason}"
      printf "REPO_NAME=%s\n" "${repo_name}"
    } > "${blocked_marker}"
    post_issue_state "${issue_number}" "BLOCKED" "Reason: ${reason}\nRepo Name: ${repo_name}\nRecovery: repair/register the workspace, then run requeue_github_issue.sh ${issue_number}." || true
  fi
}

workspace_required() {
  case "$1" in
    repo_check | ai_plan | ai_check | ai_exec) return 0 ;;
    *) return 1 ;;
  esac
}

WORKSPACE_PREFLIGHT_REASON=""
workspace_preflight() {
  local repo_name="$1"
  local config_file="${REGISTRY_DIR}/${repo_name}.env"
  local workspace_meta=""
  local source_status=0
  local config_repo_name=""
  local config_repo_path=""

  WORKSPACE_PREFLIGHT_REASON=""

  if [[ ! -r "${config_file}" ]]; then
    WORKSPACE_PREFLIGHT_REASON="WORKSPACE_NOT_REGISTERED"
    return 1
  fi

  set +e
  workspace_meta="$(
    REPO_NAME=""
    REPO_PATH=""
    LOG_DIR=""
    # Workspace configs are root-managed files created by register_workspace.sh.
    # shellcheck source=/dev/null
    . "${config_file}"
    printf '%s\n%s\n' "${REPO_NAME:-}" "${REPO_PATH:-}"
  )"
  source_status=$?
  set -e

  if [[ "${source_status}" -ne 0 ]]; then
    WORKSPACE_PREFLIGHT_REASON="WORKSPACE_CONFIG_INVALID"
    return 1
  fi

  config_repo_name="$(printf '%s\n' "${workspace_meta}" | sed -n '1p')"
  config_repo_path="$(printf '%s\n' "${workspace_meta}" | sed -n '2p')"

  if [[ -z "${config_repo_name}" || -z "${config_repo_path}" ]]; then
    WORKSPACE_PREFLIGHT_REASON="WORKSPACE_CONFIG_INCOMPLETE"
    return 1
  fi
  if [[ "${config_repo_name}" != "${repo_name}" ]]; then
    WORKSPACE_PREFLIGHT_REASON="WORKSPACE_CONFIG_MISMATCH"
    return 1
  fi
  if [[ ! -d "${config_repo_path}" || ! -x "${config_repo_path}" ]]; then
    WORKSPACE_PREFLIGHT_REASON="WORKSPACE_PATH_MISSING"
    return 1
  fi
  if ! command -v git >/dev/null 2>&1; then
    WORKSPACE_PREFLIGHT_REASON="WORKSPACE_GIT_UNAVAILABLE"
    return 1
  fi
  if ! git -C "${config_repo_path}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    WORKSPACE_PREFLIGHT_REASON="WORKSPACE_GIT_INVALID"
    return 1
  fi

  return 0
}

if ! command -v gh >/dev/null 2>&1; then
  echo "GITHUB_JOB_IMPORT_STATUS: AUTH_REQUIRED"
  echo "Reason: gh command is not installed on the VPS."
  exit 1
fi
if ! gh auth status --hostname github.com >/dev/null 2>&1; then
  echo "GITHUB_JOB_IMPORT_STATUS: AUTH_REQUIRED"
  echo "Reason: gh is not authenticated for github.com on the VPS."
  exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "GITHUB_JOB_IMPORT_STATUS: DEPENDENCY_MISSING"
  echo "Reason: jq is not installed on the VPS."
  exit 1
fi
if [[ ! "${MAX_ISSUES}" =~ ^[0-9]+$ || "${MAX_ISSUES}" -lt 1 ]]; then
  echo "GITHUB_JOB_IMPORT_STATUS: CONFIG_ERROR"
  echo "Reason: AI_COUNCIL_GITHUB_IMPORT_LIMIT must be a positive integer."
  exit 1
fi

issues_json="$(gh issue list --repo "${REPOSITORY}" --label "${LABEL}" --state open --limit "${MAX_ISSUES}" --json number,title,body,author,updatedAt)"
issue_count="$(printf "%s" "${issues_json}" | jq "length")"

if [[ "${issue_count}" -eq 0 ]]; then
  echo "GITHUB_JOB_IMPORT_STATUS: NO_MATCHING_ISSUES"
  exit 0
fi

imported_count=0
skipped_count=0
rejected_count=0
blocked_count=0
allowlist_required_count=0

while IFS= read -r row; do
  issue_json="$(printf "%s" "${row}" | base64 -d)"
  issue_number="$(printf "%s" "${issue_json}" | jq -r '.number')"
  issue_title="$(printf "%s" "${issue_json}" | jq -r '.title // ""')"
  issue_body="$(printf "%s" "${issue_json}" | jq -r '.body // ""')"
  issue_author="$(printf "%s" "${issue_json}" | jq -r '.author.login // "unknown"')"
  imported_marker="${IMPORT_DIR}/issue-${issue_number}.imported"
  blocked_marker="${BLOCKED_DIR}/issue-${issue_number}.blocked"

  if [[ -f "${imported_marker}" ]]; then
    skipped_count=$((skipped_count + 1))
    continue
  fi

  allow_status=0
  author_allowed "${issue_author}" || allow_status=$?
  case "${allow_status}" in
    0) ;;
    1)
      reject_issue "${issue_number}" "${issue_author}" "author_not_allowed"
      rejected_count=$((rejected_count + 1)); skipped_count=$((skipped_count + 1)); continue ;;
    2)
      reject_issue "${issue_number}" "${issue_author}" "allowlist_file_missing"
      rejected_count=$((rejected_count + 1)); allowlist_required_count=$((allowlist_required_count + 1)); skipped_count=$((skipped_count + 1)); continue ;;
    3)
      reject_issue "${issue_number}" "${issue_author}" "allowlist_empty"
      rejected_count=$((rejected_count + 1)); allowlist_required_count=$((allowlist_required_count + 1)); skipped_count=$((skipped_count + 1)); continue ;;
    *)
      reject_issue "${issue_number}" "${issue_author}" "allowlist_check_failed"
      rejected_count=$((rejected_count + 1)); skipped_count=$((skipped_count + 1)); continue ;;
  esac

  job_type="$(printf "%s\n" "${issue_body}" | awk -F= '/^JOB_TYPE=/{print $2; exit}' | tr -d '[:space:]')"
  repo_name="$(printf "%s\n" "${issue_body}" | awk -F= '/^REPO_NAME=/{print $2; exit}' | tr -d '[:space:]')"
  request_mode="explicit"

  if [[ -z "${job_type}" ]]; then
    if derive_casual_job "${issue_title}
${issue_body}"; then
      request_mode="casual"
    else
      job_type="ai_plan"
      repo_name="${repo_name:-ai-council}"
      request_mode="freeform_plan"
      echo "Routing issue #${issue_number}: free-form request -> ai_plan"
    fi
  fi

  case "${job_type}" in
    repo_check)
      if [[ -z "${repo_name}" ]]; then
        reject_issue "${issue_number}" "${issue_author}" "repo_check_requires_repo_name"
        rejected_count=$((rejected_count + 1)); skipped_count=$((skipped_count + 1)); continue
      fi
      ;;
    workspace_summary) repo_name="${repo_name:-all}" ;;
    ai_plan | ai_check | ai_exec) repo_name="${repo_name:-ai-council}" ;;
    *)
      reject_issue "${issue_number}" "${issue_author}" "unsupported_or_missing_job_type"
      rejected_count=$((rejected_count + 1)); skipped_count=$((skipped_count + 1)); continue ;;
  esac

  if [[ ! "${repo_name}" =~ ^[A-Za-z0-9._-]+$ ]]; then
    reject_issue "${issue_number}" "${issue_author}" "unsafe_repo_name"
    rejected_count=$((rejected_count + 1)); skipped_count=$((skipped_count + 1)); continue
  fi

  if workspace_required "${job_type}" && ! workspace_preflight "${repo_name}"; then
    block_issue "${issue_number}" "${issue_author}" "${WORKSPACE_PREFLIGHT_REASON:-WORKSPACE_PREFLIGHT_FAILED}" "${repo_name}"
    blocked_count=$((blocked_count + 1)); skipped_count=$((skipped_count + 1)); continue
  fi

  if [[ -f "${blocked_marker}" ]]; then
    rm -f "${blocked_marker}"
    post_issue_state "${issue_number}" "DISCOVERED" "Previous workspace blocker cleared. Import is resuming." || true
  fi

  set +e
  create_output="$(AI_COUNCIL_REQUEST_SOURCE="github_issue_${issue_number}" AI_COUNCIL_REQUESTED_BY="${issue_author}" bash "${APP_DIR}/scripts/create_job.sh" "${job_type}" "${repo_name}" 2>&1)"
  create_status=$?
  set -e

  if [[ "${create_status}" -ne 0 ]]; then
    block_issue "${issue_number}" "${issue_author}" "JOB_CREATE_FAILED" "${repo_name}"
    printf "%s issue=%s create_status=%s\n" "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" "${issue_number}" "${create_status}" >> "${LOG_DIR}/create-job-errors.log"
    blocked_count=$((blocked_count + 1)); skipped_count=$((skipped_count + 1)); continue
  fi

  job_id="$(printf "%s\n" "${create_output}" | awk -F= '/JOB_ID=/{print $2; exit}' | tr -d '[:space:]')"
  if [[ -z "${job_id}" ]]; then
    block_issue "${issue_number}" "${issue_author}" "JOB_ID_MISSING" "${repo_name}"
    blocked_count=$((blocked_count + 1)); skipped_count=$((skipped_count + 1)); continue
  fi

  {
    echo "ISSUE_NUMBER=${issue_number}"
    echo "JOB_ID=${job_id}"
    echo "JOB_TYPE=${job_type}"
    echo "REPO_NAME=${repo_name}"
    echo "REQUEST_MODE=${request_mode}"
    echo "STATE=QUEUED"
    echo "IMPORTED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  } > "${imported_marker}"

  printf "%s\n" "${create_output}"
  echo "Imported GitHub Issue #${issue_number} as job ${job_id}"
  post_issue_state "${issue_number}" "QUEUED" "Job ID: ${job_id}\nJob Type: ${job_type}\nRepo Name: ${repo_name}" || true
  imported_count=$((imported_count + 1))
done < <(printf "%s" "${issues_json}" | jq -r '.[] | @base64')

echo "Imported: ${imported_count}"
echo "Skipped: ${skipped_count}"
echo "Rejected: ${rejected_count}"
echo "Blocked: ${blocked_count}"
echo "Allowlist File: ${ALLOWLIST_FILE}"

if [[ "${imported_count}" -eq 0 && "${allowlist_required_count}" -gt 0 ]]; then
  echo "GITHUB_JOB_IMPORT_STATUS: ALLOWLIST_REQUIRED"
elif [[ "${blocked_count}" -gt 0 ]]; then
  echo "GITHUB_JOB_IMPORT_STATUS: PARTIAL_BLOCKED"
else
  echo "GITHUB_JOB_IMPORT_STATUS: OK"
fi
